apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1-deployment
  namespace: demo
  labels:
    app: api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
        - name: test-container
          image: peishu/api1:v1
          env:
            # Define the environment variable
            - name: SPECIAL_LEVEL_KEY
              valueFrom:
                configMapKeyRef:
                  name: special-config
                  key: special.how
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: test-db-secret
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-db-secret
                  key: password

            